version: "3.9"

services:
  db:
    image: postgres:16
    container_name: amritakalotsav_db
    environment:
      POSTGRES_DB: amritakalotsav_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: nandandev/amritakalotsav-backend:latest
    container_name: amritakalotsav_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=amritakalotsav_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres123

volumes:
  pgdata:
