version: "3.9"

services:
  db:
    image: postgres:16
    container_name: amritakalotsav_db
    environment:
      POSTGRES_DB: amritakalotsav_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: nandandev/amritakalotsav-backend:latest
    container_name: amritakalotsav_backend
    command: >
      sh -c "python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./cred.json:/app/cred.json

volumes:
  pgdata:
